// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockoApi.Infrastructure.Datastore.EF;

#nullable disable

namespace StockoApi.Infrastructure.Datastore.EF.Migrations
{
    [DbContext(typeof(StockoDbContext))]
    [Migration("20261002162314_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stocko")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockoApi.Domain.TickerSnapshot", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DividendRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<double>("DividendYield")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("date");

                    b.Property<double>("HeldPercentInsiders")
                        .HasColumnType("float");

                    b.Property<double>("HeldPercentInstitutions")
                        .HasColumnType("float");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IndustryKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("LastDividendDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastDividendDecrease")
                        .HasColumnType("date");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<double>("PayoutRatio")
                        .HasColumnType("float");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("RegularMarketPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<long>("RegularMarketTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SectorKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TtmDivs")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("TypeDisp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("YearsConsecutiveDividendIncrease")
                        .HasColumnType("int");

                    b.Property<int>("YearsSinceDividendDecrease")
                        .HasColumnType("int");

                    b.HasKey("Symbol", "SnapshotDate");

                    b.ToTable("TickerSnapshots", "stocko");
                });
#pragma warning restore 612, 618
        }
    }
}
